"""
src/models/events.py
Re-exports everything from the canonical schema.
Single source of truth is schema/events.py — never redefine here.
"""
from schema.events import (
    BaseEvent,
    EVENT_REGISTRY,
    deserialize_event,
    # Enums
    RiskTier,
    ApplicationState,
    DocumentType,
    DocumentFormat,
    AgentType,
    LoanPurpose,
    FraudAnomalyType,
    ComplianceVerdict,
    # Value objects
    FinancialFacts,
    FraudAnomaly,
    CreditDecision,
    # All 45 event classes
    ApplicationSubmitted,
    DocumentUploadRequested,
    DocumentUploaded,
    DocumentUploadFailed,
    CreditAnalysisRequested,
    FraudScreeningRequested,
    ComplianceCheckRequested,
    DecisionRequested,
    DecisionGenerated,
    HumanReviewRequested,
    HumanReviewCompleted,
    ApplicationApproved,
    ApplicationDeclined,
    PackageCreated,
    DocumentAdded,
    DocumentFormatValidated,
    DocumentFormatRejected,
    ExtractionStarted,
    ExtractionCompleted,
    ExtractionFailed,
    QualityAssessmentCompleted,
    PackageReadyForAnalysis,
    AgentSessionStarted,
    AgentInputValidated,
    AgentInputValidationFailed,
    AgentNodeExecuted,
    AgentToolCalled,
    AgentOutputWritten,
    AgentSessionCompleted,
    AgentSessionFailed,
    AgentSessionRecovered,
    CreditRecordOpened,
    HistoricalProfileConsumed,
    ExtractedFactsConsumed,
    CreditAnalysisCompleted,
    CreditAnalysisDeferred,
    ComplianceCheckInitiated,
    ComplianceRulePassed,
    ComplianceRuleFailed,
    ComplianceRuleNoted,
    ComplianceCheckCompleted,
    FraudScreeningInitiated,
    FraudAnomalyDetected,
    FraudScreeningCompleted,
    AuditIntegrityCheckRun,
)

__all__ = [
    "BaseEvent", "EVENT_REGISTRY", "deserialize_event",
    "RiskTier", "ApplicationState", "DocumentType", "DocumentFormat",
    "AgentType", "LoanPurpose", "FraudAnomalyType", "ComplianceVerdict",
    "FinancialFacts", "FraudAnomaly", "CreditDecision",
    "ApplicationSubmitted", "DocumentUploadRequested", "DocumentUploaded",
    "DocumentUploadFailed", "CreditAnalysisRequested", "FraudScreeningRequested",
    "ComplianceCheckRequested", "DecisionRequested", "DecisionGenerated",
    "HumanReviewRequested", "HumanReviewCompleted", "ApplicationApproved",
    "ApplicationDeclined", "PackageCreated", "DocumentAdded",
    "DocumentFormatValidated", "DocumentFormatRejected", "ExtractionStarted",
    "ExtractionCompleted", "ExtractionFailed", "QualityAssessmentCompleted",
    "PackageReadyForAnalysis", "AgentSessionStarted", "AgentInputValidated",
    "AgentInputValidationFailed", "AgentNodeExecuted", "AgentToolCalled",
    "AgentOutputWritten", "AgentSessionCompleted", "AgentSessionFailed",
    "AgentSessionRecovered", "CreditRecordOpened", "HistoricalProfileConsumed",
    "ExtractedFactsConsumed", "CreditAnalysisCompleted", "CreditAnalysisDeferred",
    "ComplianceCheckInitiated", "ComplianceRulePassed", "ComplianceRuleFailed",
    "ComplianceRuleNoted", "ComplianceCheckCompleted", "FraudScreeningInitiated",
    "FraudAnomalyDetected", "FraudScreeningCompleted", "AuditIntegrityCheckRun",
]